 const resList = [
    {
      id: 81191,
      name: "Velu Military Hotel",
      city: "Chennai - T. Nagar",
      cuisines: ["South Indian", "Briyani"],
      restaurant: "velu-military-hotel-t-nagar",
      city: "chennai",
      rating: 4.6,
      eta: "15-20 minutes",
    },
    {
      id: 81192,
      name: "Murugan Idli Shop",
      city: "Chennai - Anna Nagar",
      cuisines: ["South Indian", "Vegetarian"],
      restaurant: "murugan-idli-shop-anna-nagar",
      city: "chennai",
      rating: 4.4,
      eta: "10-15 minutes",
    },
    {
      id: 81193,
      name: "SS Hyderabad Briyani",
      city: "Chennai - Velachery",
      cuisines: ["Briyani", "North Indian", "Chinese"],
      restaurant: "ss-hyderabad-briyani-velachery",
      city: "chennai",
      rating: 4.3,
      eta: "20-25 minutes",
    },
    {
      id: 81194,
      name: "Anjappar Chettinad Restaurant",
      city: "Chennai - Adyar",
      cuisines: ["Chettinad", "South Indian", "Chinese"],
      restaurant: "anjappar-chettinad-adyar",
      city: "chennai",
      rating: 4.2,
      eta: "15-20 minutes",
    },
    {
      id: 81195,
      name: "Hot Chips",
      city: "Chennai - Tambaram",
      cuisines: ["Fast Food", "South Indian"],
      restaurant: "hot-chips-tambaram",
      city: "chennai",
      rating: 4.1,
      eta: "10-15 minutes",
    },
    {
      id: 81196,
      name: "Aasife Biriyani",
      city: "Chennai - Porur",
      cuisines: ["Briyani", "Indian", "Chinese"],
      restaurant: "aasife-biriyani-porur",
      city: "chennai",
      rating: 4.5,
      eta: "20-25 minutes",
    },
    {
      id: 81197,
      name: "Pind Punjabi Dhaba",
      city: "Chennai - Ashok Nagar",
      cuisines: ["North Indian", "Punjabi", "Tandoor"],
      restaurant: "pind-punjabi-dhaba-ashok-nagar",
      city: "chennai",
      rating: 4.4,
      eta: "15-20 minutes",
    },
    {
      id: 81198,
      name: "Dindigul Thalappakatti",
      city: "Chennai - OMR",
      cuisines: ["Briyani", "South Indian"],
      restaurant: "dindigul-thalappakatti-omr",
      city: "chennai",
      rating: 4.6,
      eta: "15-20 minutes",
    },
    {
      id: 81199,
      name: "Writer's Cafe",
      city: "Chennai - Nungambakkam",
      cuisines: ["Cafe", "Italian", "Desserts"],
      restaurant: "writers-cafe-nungambakkam",
      city: "chennai",
      rating: 4.7,
      eta: "10-15 minutes",
    },
    {
      id: 81200,
      name: "The Marina",
      city: "Chennai - Besant Nagar",
      cuisines: ["Seafood", "South Indian"],
      restaurant: "the-marina-besant-nagar",
      city: "chennai",
      rating: 4.5,
      eta: "15-20 minutes",
    },
    {
      id: 81201,
      name: "Zaitoon",
      city: "Chennai - ECR",
      cuisines: ["Middle Eastern", "North Indian", "Chinese"],
      restaurant: "zaitoon-ecr",
      city: "chennai",
      rating: 4.3,
      eta: "20-25 minutes",
    },
    {
      id: 81190,
      name: "Ambur Star Briyani Since 1890",
      city: "Madurai",
      cuisines: ["Briyani", "South Indian", "chinese", "North Indian"],
      restaurant: "ambur-star-biryani-arrapalayam-ss-colony",
      city: "madurai",
      rating: 4.5,
      eta: "10-15 minutes",
    },
  ];

export default resList